export const SET_REGISTER_DATA = "SET_REGISTER_DATA";
export const SET_VALIDATATION_ERROR = "SET_VALIDATATION_ERROR";
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const SET_RESEND_CODE_DATA = "SET_RESEND_CODE_DATA";
export const SET_FORGET_USER_DATA = "SET_FORGET_USER_DATA";
export const SET_LOGIN_DATA = "SET_LOGIN_DATA";
export const SET_PROFILE_BASIC_DETAILS = "SET_PROFILE_BASIC_DETAILS";
export const SET_UPDATE_FORM = "SET_UPDATE_FORM";

export const PROFILE_FIELD_CHANGE = "PROFILE_FIELD_CHANGE";
